#:kivy 1.0

<FishLifeIntro>:
    go_btn: button
    help_btn: help
    
    canvas:
        Color:
            rgb: (1,1,1)
        Rectangle:
            source: "images/welcome.png"
            size: self.size
    
    Button:
        id: help
        text: "HowToPlay"
        center: root.center_x, root.height / 2
    
    Button:
        id: button
        text: "Feed the fish!"
        center: root.center_x, self.height / 2
